// Package integration owns the authoritative agent-facing documentation that
// autoresearch writes into a target project's .claude/ directory. Keeping the
// content in a Go package (not a loose template file) lets `autoresearch init`
// and `autoresearch claude install` share the same source of truth and
// version-bump it atomically.
package integration

import "strings"

// ClaudeDocRelPath is the path to write under the target project, relative to
// the project root.
const ClaudeDocRelPath = ".claude/autoresearch.md"

// ClaudeDoc returns the full content of .claude/autoresearch.md. The opening
// warning and the managed sentinels make it obvious to a future editor that
// autoresearch owns this file.
func ClaudeDoc(moduleVersion string) string {
	return strings.ReplaceAll(claudeDocTemplate, "{{version}}", moduleVersion)
}

const claudeDocTemplate = `<!-- autoresearch:managed -->
<!--
  This file is generated by ` + "`autoresearch init`" + ` and ` + "`autoresearch claude install`" + `.
  Edits will be overwritten. Add your own project notes to CLAUDE.md instead
  and, if you want this reference loaded into your main session, put
  ` + "`@.claude/autoresearch.md`" + ` in your CLAUDE.md.

  autoresearch version: {{version}}
-->

# autoresearch — agent reference

` + "`autoresearch`" + ` is a scientific-research CLI installed in this project. It
treats Claude as an agentic researcher, with a strict firewall between
speculation and observation enforced by the CLI itself.

## Your role when the human talks to you

The human's interface to autoresearch is **conversation with you**, not
YAML authoring or file editing. When a human says:

| Human says | You do |
|---|---|
| "Goal: reduce dsp_fir cycles by 20%, keep flash ≤ 64 KB, tests must pass" | ` + "`autoresearch goal set`" + ` with ` + "`--objective-*`" + ` and ` + "`--constraint-*`" + ` flags |
| "Also: no assembly, start with loop unrolling" | ` + "`autoresearch steering append \"no assembly\"`" + `, then another append for the second note |
| "Try unrolling by 8 as a priority" | ` + "`autoresearch hypothesis add --author human:you`" + ` + ` + "`hypothesis promote <id> --reason \"...\"`" + ` |
| "H-0003 is a dead end" | ` + "`autoresearch hypothesis kill H-0003 --reason \"...\"`" + ` |
| "Pause, I want to look at E-0005" | ` + "`autoresearch pause --reason \"human review of E-0005\"`" + ` |
| "Resume" | ` + "`autoresearch resume`" + ` |
| "What's the current best?" | ` + "`autoresearch frontier`" + `, summarize |
| "Show me the writeup for H-0001" | ` + "`autoresearch report H-0001`" + ` |
| "What just happened?" | ` + "`autoresearch log --tail 30`" + ` |
| "What have we learned so far?" | ` + "`autoresearch lesson list --status active`" + `, summarize |

**Never** ask the human to author YAML or edit files under ` + "`.research/`" + ` or
` + "`goal.md`" + ` directly. They can if they want to, but you should not require it.
Translate every conversational intent into exactly one CLI call and echo
back a short confirmation.

## Exit codes

The binary uses specific exit codes so orchestrators can react:

- ` + "`0`" + ` — success
- ` + "`1`" + ` — generic error
- ` + "`2`" + ` — cobra flag/usage error
- ` + "`3`" + ` — autoresearch is **paused**. Stop the loop; tell the human and wait for ` + "`resume`" + `.
- ` + "`4`" + ` — **budget exhausted**. Stop designing new experiments; finish in-flight work; tell the human.

In ` + "`--json`" + ` mode errors also surface a specific structure, but the exit
code is the authoritative signal for the orchestrator loop.

## Scope

**Use autoresearch for**: optimizing a **working codebase** toward a
measurable goal (speed, size, energy, accuracy, memory, anything with a
registered instrument).

**Do not use autoresearch for**: building features from a spec, writing new
modules from scratch, or anything whose success is "tests pass" rather than
"the number moved by X%". Feature delivery belongs to a different tool.

If the goal looks like *"implement X"* rather than *"make X faster / smaller /
more accurate"*, stop and tell the user. ` + "`autoresearch goal set`" + ` will reject a
goal whose objective has no ` + "`instrument:`" + ` field.

## The CLI is the only writer

You cannot edit anything under ` + "`.research/`" + ` directly. The only way to
record a hypothesis, observation, or conclusion is through the CLI. Every
observation is backed by a content-addressed raw artifact on disk. Every
verdict passes through a strict-mode firewall. If you edit ` + "`.research/`" + ` files
by hand, you are lying to future-you — don't.

## Entity lifecycle

    hypothesis (open)
      └─> experiment design  (status: designed)
           └─> experiment implement  (status: implemented)  -- git worktree created
                └─> observe          (status: measured)     -- instruments run, artifacts stored
                     └─> conclude     (status: analyzed)    -- stats firewall applied
                          └─> hypothesis: supported | refuted | inconclusive

Backward transitions are explicit and auditable:

- ` + "`hypothesis kill <id> --reason '...'`" + ` moves a hypothesis to ` + "`killed`" + `.
- ` + "`hypothesis reopen <id> --reason '...'`" + ` un-kills it.
- ` + "`experiment reset <id> --reason '...'`" + ` drops an implemented/measured
  experiment back to ` + "`designed`" + ` **and preserves the abandoned git branch** as
  ` + "`autoresearch/<exp-id>@<unix-millis>`" + ` so any commits the previous attempt
  made remain inspectable.

Reasons are required on every backward move and recorded in ` + "`events.jsonl`" + `.

## Command surface

Everything supports ` + "`--json`" + ` for structured output and ` + "`--dry-run`" + ` where
mutations happen. ` + "`--project-dir`" + ` / ` + "`-C`" + ` is global. Invoke ` + "`<verb> --help`" + ` for
flag details.

### Lifecycle
    autoresearch init       --build-cmd ... --test-cmd ...
    autoresearch status
    autoresearch log        [--tail N] [--kind prefix] [--since RFC3339]
    autoresearch pause      [--reason "..."]
    autoresearch resume

### Budgets
    autoresearch budget show
    autoresearch budget set --max-experiments N --max-wall-time-h H --frontier-stall-k K
        # Pass -1 to clear a specific limit; 0 leaves it unchanged.

### Goal and steering (flag-form, no YAML needed)
    autoresearch goal set \
        --objective-instrument qemu_cycles \
        --objective-target dsp_fir \
        --objective-direction decrease \
        --objective-target-effect 0.20 \
        --constraint-max 'size_flash=65536' \
        --constraint-require 'host_test=pass' \
        --steering "start with loop unrolling"
    autoresearch goal set --file goal.md        # for humans who prefer editor workflows
    autoresearch goal show
    autoresearch steering show
    autoresearch steering append "avoid assembly, portable C only"
    autoresearch hypothesis reopen <hyp-id> --reason "..."

### Hypotheses
    autoresearch hypothesis add \
        --claim "..." \
        --predicts-instrument NAME --predicts-target T --predicts-direction {increase|decrease} --predicts-min-effect F \
        --kill-if "..." [--kill-if "..."] [--parent H-XXXX] [--author human:alice]
    autoresearch hypothesis list    [--status ...] [--parent ...]
    autoresearch hypothesis show    <hyp-id>
    autoresearch hypothesis kill    <hyp-id> --reason "..."
    autoresearch hypothesis reopen  <hyp-id> --reason "..."
    autoresearch hypothesis promote <hyp-id> --reason "..."  # mark priority:human
    autoresearch tree               [--root H-XXXX]
    autoresearch frontier                                  # best-first, stalled_for
    autoresearch report             <hyp-id>               # markdown writeup

### Experiments
    autoresearch experiment design     <hyp-id> --tier {host|qemu|hardware} --instruments a,b,c --baseline HEAD
    autoresearch experiment implement  <exp-id>
    autoresearch experiment reset      <exp-id> --reason "..."
    autoresearch experiment worktree   <exp-id>
    autoresearch experiment list       [--tier ...] [--status ...] [--hypothesis ...]
    autoresearch experiment show       <exp-id>

Tier gate: ` + "`qemu`" + ` requires a prior host-tier experiment on the same
hypothesis (or ` + "`--force`" + `); ` + "`hardware`" + ` always requires ` + "`--force`" + `.

### Observations and analysis
    autoresearch observe  <exp-id> --instrument NAME [--samples N]
    autoresearch analyze  <exp-id> [--baseline <baseline-exp-id>] [--instrument NAME] [--iters N]
    autoresearch conclude <hyp-id> \
        --verdict {supported|refuted|inconclusive} \
        --observations O-XXXX,O-YYYY \
        [--baseline-experiment E-XXXX] \
        [--interpretation "..."]

### Conclusions (review and critic)
    autoresearch conclusion list       [--hypothesis H-XXXX] [--verdict X]
    autoresearch conclusion show       <C-id>
    autoresearch conclusion downgrade  <C-id> --reason "..." [--reviewed-by agent:critic]
        # Critic's sole mutation: flips supported|refuted → inconclusive,
        # preserving the original verdict in strict_check.downgraded_from.

### Artifact navigation (bounded by default)
    autoresearch artifact list   [--experiment E-XXXX | --observation O-XXXX]
    autoresearch artifact stat   <sha-or-prefix>
    autoresearch artifact path   <sha-or-prefix>
    autoresearch artifact head   <sha> [--lines N]         # default 50
    autoresearch artifact tail   <sha> [--lines N]         # default 50
    autoresearch artifact range  <sha> --from L1 --to L2
    autoresearch artifact grep   <sha> <regex> [--context C] [--max-matches N]  # defaults: context=0 max=100
    autoresearch artifact diff   <sha-a> <sha-b> [--context C] [--max-lines N]  # defaults: context=3 max=500
    autoresearch artifact show   <sha> [--max-bytes B | --all]                 # default 256 KB, refuses larger

### Instruments
    autoresearch instrument register <name> \
        --cmd a,b,c \
        --parser builtin:{passfail|timing|size|scalar} \
        [--pattern 'regex with one capture group']  # required for builtin:scalar
        --unit U --tier {host|qemu|hardware} [--min-samples N]
    autoresearch instrument list

Built-in parsers:

- ` + "`builtin:passfail`" + ` — run once; value=1 on exit 0, else 0. For build/test
  gates and any binary outcome.
- ` + "`builtin:timing`" + `  — run N times; wall-time mean with BCa 95% CI. Unit is
  always ` + "`seconds`" + `.
- ` + "`builtin:size`" + `    — run once; first numeric column of ` + "`size(1)`" + ` output
  (Berkeley or Mach-O); all columns land in aux.
- ` + "`builtin:scalar`" + `  — run N times; extract a single integer from each
  stdout using ` + "`--pattern`" + ` (RE2 regex, exactly one capture group). Aggregate
  with BCa 95% CI. The unit is whatever you declare at registration. This is
  the parser for anything that prints a number: qemu semihosting cycle
  counts, ` + "`perf stat` " + `counters, ` + "`objdump`" + ` symbol counts, cachegrind misses,
  lizard complexity, LOC, page-fault counts — the parser is generic.

Examples of ` + "`builtin:scalar`" + ` instruments (the name is your choice):

    # Cycles reported by semihosting from firmware running under qemu:
    autoresearch instrument register qemu_cycles \
        --cmd qemu-system-arm,-machine,mps2-an386,-kernel,firmware.elf,-icount,shift=0,-nographic,-semihosting-config,enable=on,target=native \
        --parser builtin:scalar \
        --pattern 'cycles:\s*(\d+)' \
        --unit cycles --tier qemu --min-samples 3

    # Retired instructions from perf stat on host:
    autoresearch instrument register perf_instructions \
        --cmd sh,-c,"perf stat -e instructions ./build/main 2>&1" \
        --parser builtin:scalar \
        --pattern '([0-9,]+)\s+instructions' \
        --unit instructions --tier host --min-samples 5

    # Cyclomatic complexity reported by lizard:
    autoresearch instrument register ccn_avg_x100 \
        --cmd sh,-c,"lizard -C 0 src/ | awk '/Avg.CCN/ {printf \"avg_ccn_x100: %d\\n\", $1*100}'" \
        --parser builtin:scalar \
        --pattern 'avg_ccn_x100:\s*(\d+)' \
        --unit ccn_x100 --tier host

The parser requires an integer. If your tool emits a fractional number,
scale it (as in the ccn example). If your tool emits multiple metrics,
register multiple instruments with different patterns.

## Strict-mode firewall

The CLI refuses structurally sloppy entries. You cannot work around these —
fix the input instead.

- ` + "`hypothesis add`" + `: requires claim, predicts.{instrument,target,direction,
  min_effect}, and at least one ` + "`--kill-if`" + ` clause. Missing any is exit 1.
- ` + "`goal set`" + `: rejects goals whose ` + "`objective.instrument`" + ` is not in the
  registered instruments, including goals with no instrument at all (feature
  delivery goals).
- ` + "`experiment design`" + `: instruments must be registered; killed hypotheses
  refuse new experiments; tier gate as above.
- ` + "`observe`" + `: experiment must be ` + "`implemented`" + ` or later; instrument must be
  registered; strict mode rejects ` + "`--samples N`" + ` below the instrument's
  ` + "`min_samples`" + `.
- ` + "`conclude`" + `: will **downgrade** a requested ` + "`supported`" + ` verdict to
  ` + "`inconclusive`" + ` if:
    - the 95% CI on the fractional effect crosses zero in the wrong direction, OR
    - ` + "`|delta_frac| < hypothesis.predicts.min_effect`" + `.
  Every downgrade is recorded in the conclusion's ` + "`strict_check`" + ` block and
  in ` + "`events.jsonl`" + ` as a ` + "`conclusion.downgrade`" + ` event. The conclusion still
  persists; the hypothesis moves to ` + "`inconclusive`" + `.

## The notebook layer

Beside the per-cycle artifacts (hypotheses, experiments, observations,
conclusions), the store holds a **notebook** — prose that carries
reasoning across cycles. Three kinds:

**1. Per-entity rationale** — every mutation verb that produces a new
entity takes a prose flag that lands on the entity's ` + "`body`" + ` field,
readable via ` + "`<entity> show <id> --json | jq .body`" + `:

- ` + "`hypothesis add --rationale \"...\"`" + ` — why this hypothesis, what
  evidence or lesson led you here. Required on every call.
- ` + "`experiment design --design-notes \"...\"`" + ` — why these instruments,
  this tier, this baseline. Required on every call.
- ` + "`experiment implement --impl-notes \"...\"`" + ` — what you noticed while
  applying the change; trade-offs, edge cases, anything surprising.
  Required on every call.
- ` + "`conclude --interpretation \"...\"`" + ` — one paragraph grounded in the
  observed numbers, linking mechanism to effect.

The rationale lives on the entity record forever; the first ~200 chars
also land on the event payload so ` + "`log --follow`" + ` watchers see the gist
in-stream.

**2. Lessons** (` + "`L-NNNN`" + `) — supersedable one-sentence claims the loop
has learned. Unlike per-cycle artifacts, lessons sit *above* them and
are meant to inform the next cycle. Two scopes:

- ` + "`scope: hypothesis`" + ` — tied to one or more H-/E-/C- ids the lesson
  was extracted from. Written by the analyst on decisive verdicts and
  by the critic on cross-cutting downgrades.
- ` + "`scope: system`" + ` — free-floating findings about the target codebase or
  the research apparatus itself ("the test harness caches fixtures",
  "qemu variance correlates with CPU temperature"). No hypothesis
  reference required. Any agent that reviews observation artifacts can
  record one.

Verbs:

    autoresearch lesson add --claim "..." --body "..." [--from C-NNNN,H-NNNN] [--scope ...] [--tag ...]
    autoresearch lesson list [--scope ...] [--status ...] [--subject ...] [--tag ...]
    autoresearch lesson show <L-id>
    autoresearch lesson supersede <L-old> --by <L-new> --reason "..."

Scope is inferred from ` + "`--from`" + ` when not explicit: subjects given →
` + "`hypothesis`" + `; none → ` + "`system`" + `.

**` + "`--body`" + ` is not optional for agents.** A lesson that is only a
` + "`--claim`" + ` is a one-liner the next generator cannot act on; that
defeats the point of the notebook layer. Every lesson written by an
agent MUST have a body with these four sections, in this order:

1. ` + "`## Evidence`" + ` — the specific numbers, cited with their C-id /
   E-id / O-id. Include ` + "`delta_frac`" + `, CI, ` + "`p_value`" + `, and n for every
   number.
2. ` + "`## Mechanism`" + ` — *why* the claim is true. Link the code change
   on the experiment branch to the measured effect. "Unrolling is
   faster" is not a mechanism.
3. ` + "`## Scope and counterexamples`" + ` — the conditions this applies
   under (target metric, sizes, tier, compile flags) AND at least
   one condition where it would NOT apply. Lessons without boundaries
   turn into superstition.
4. ` + "`## For the next generator`" + ` — one or two concrete suggestions a
   future generator can pick up. "Keep investigating" is not actionable.

If an agent cannot fill all four sections honestly, the claim was not
decisive enough to be a lesson — mark the conclusion ` + "`inconclusive`" + `
instead of writing a thin lesson. The subagent briefs under
` + "`.claude/agents/research-{analyst,critic}.md`" + ` have a full worked
example.

**3. The reading contract.** Lessons are load-bearing, not decorative:

- The **generator** MUST run ` + "`lesson list --status active --json`" + ` as
  part of "read before speaking". Its ` + "`--rationale`" + ` must either cite a
  lesson ID or explicitly note "no relevant lesson". This keeps the
  notebook from rotting.
- The **analyst** MUST call ` + "`lesson add`" + ` on any decisive conclusion
  (supported, or cleanly refuted with a mechanism). If you cannot
  state a one-sentence reusable claim, the verdict was not decisive —
  mark it inconclusive instead.
- The **critic** MAY call ` + "`lesson add`" + ` on downgrade, but only for
  cross-cutting patterns. One-off reasons stay in
  ` + "`conclusion.strict_check.reasons`" + `.
- The **observer** NEVER writes prose of any kind. The
  speculation/observation firewall applies. If something surprises the
  observer, the analyst or critic picks it up from the artifacts and
  records a ` + "`scope: system`" + ` lesson.

Supersession forms chains: ` + "`lesson add`" + ` the replacement first, then
` + "`lesson supersede L-old --by L-new --reason \"...\"`" + `. The store updates
both sides — ` + "`L-old.status=superseded, L-old.superseded_by=L-new`" + ` and
` + "`L-new.supersedes=L-old`" + `. The generator reads
` + "`lesson list --status active`" + ` by default and will not see superseded
records.

## Capturing allocated IDs

The CLI allocates every entity ID server-side (` + "`H-0001`" + `, ` + "`E-0001`" + `,
` + "`O-0001`" + `, ` + "`C-0001`" + `). Do **not** guess or hardcode these — start a fresh
store and you'll get H-0001, but in any real run the numbering depends on
what's already there.

Every creation verb exposes the new id at the top level of its ` + "`--json`" + `
response. Capture with:

    H1=$(autoresearch hypothesis add ...  --json | jq -r .id)
    E1=$(autoresearch experiment design $H1 ... --json | jq -r .id)
    O1=$(autoresearch observe $E1 --instrument host_timing --json | jq -r .id)
    C1=$(autoresearch conclude $H1 --verdict supported --observations $O1 ... --json | jq -r .id)

The same works from any JSON library. In text mode, the first line of the
success output always has the new id as its second word
(` + "`added H-0001`" + `, ` + "`designed E-0001 for H-0001`" + `, ` + "`recorded O-0001`" + `,
` + "`wrote C-0001`" + `), so ` + "`awk '{print $2}'`" + ` works if you must.

## Bounded output — read the header line

**Every bounded command prints its applied defaults** as the first line of
output, both in text mode and in ` + "`--json`" + ` (under the ` + "`limits`" + ` key). When
you see:

    [defaults applied: lines=50]  (override with flags; see --help)
    [file: artifacts/ab/cdef.../disasm.txt, 540000 lines total]

the output is **not** the full file. Do not treat it as the golden answer.
Use the slicing verbs (` + "`range`" + `, ` + "`grep`" + `, ` + "`--lines`" + `) or raise the flag to go
deeper. In ` + "`--json`" + `, check ` + "`truncated`" + ` and ` + "`total_lines`" + ` / ` + "`total_matches`" + `
alongside the payload.

` + "`artifact show`" + ` refuses files above 256 KB by default and points you at the
slicing verbs — do not override with ` + "`--all`" + ` unless you specifically need
the whole thing.

## File layout

    <project>/.research/           ← gitignored; autoresearch state, not tracked in the main repo
      config.yaml         — instruments registry, build+test commands, worktrees.root, budgets, mode
      goal.md             — objective + constraints + human steering (YAML frontmatter + markdown body)
      state.json          — counters, pause flag, last-event cursor
      events.jsonl        — append-only event log (machine source of truth)
      hypotheses/<id>.md
      experiments/<id>.md
      observations/<id>.json
      conclusions/<id>.md
      artifacts/<sha[:2]>/<sha[2:]>/<filename>  — content-addressed raw outputs

    <project>/.claude/             ← tracked in the main repo (shared team infra)
      autoresearch.md     — this file, generated, managed
      agents/research-*.md — subagent prompts (M9+), generated, managed

` + "`.research/`" + ` is **not** versioned in the main project repo. ` + "`autoresearch init`" + `
adds ` + "`.research/`" + ` to ` + "`.gitignore`" + ` (creating it if needed, appending only if
missing). It is runtime state, per-engineer, regenerable from the code and
the goal. The ` + "`.claude/`" + ` files, by contrast, are shared team infrastructure
and should be committed.

Worktrees live **outside** the project tree. Default path is under the user
cache dir, keyed by ` + "`<basename>-<8hex-of-abspath-hash>`" + `. Override by editing
` + "`.research/config.yaml → worktrees.root`" + `. Naive ` + "`grep -r`" + ` / ` + "`find`" + ` from the
project root cannot accidentally descend into any experiment worktree — this
is by design.

## Working from a subdirectory

` + "`autoresearch`" + ` commands find the store by walking up from the current
directory (the same discovery ` + "`git`" + ` uses for ` + "`.git`" + `). You can run
` + "`autoresearch status`" + ` from ` + "`src/inner/deep/`" + ` and it will find the project's
` + "`.research/`" + `. Running from inside an experiment worktree (which lives outside
the project tree entirely) intentionally does NOT find the main store —
those worktrees are a different directory subtree and a fresh ` + "`autoresearch`" + `
invocation from in there would have no anchor. If you need to operate on
the main store from a worktree context, pass ` + "`-C <project-root>`" + ` explicitly.

## Idempotent state transitions

    hypothesis.add         → H-XXXX (status: open)
    hypothesis.kill        → status: killed      (requires --reason)
    hypothesis.reopen      → status: open        (requires --reason; from killed only)
    experiment.design      → E-XXXX (status: designed)
    experiment.implement   → status: implemented (creates git worktree)
    experiment.reset       → status: designed    (requires --reason; preserves branch)
    observation.record     → O-XXXX; experiment: implemented → measured (first obs only)
    conclusion.write       → C-XXXX; experiment: measured → analyzed; hypothesis: open → {supported|refuted|inconclusive}
    conclusion.downgrade   → same as write, but the conclusion records what was downgraded and why

## Watching the loop

When you want to see what's happening across the whole research state without
spamming four separate verbs:

    autoresearch dashboard              # one-shot composite snapshot
    autoresearch dashboard --refresh 2  # live, auto-refreshes every 2 seconds
    autoresearch log --follow           # tail events.jsonl as new events land

The dashboard composes goal + budget + hypothesis tree + frontier + in-flight
experiments + recent events into one frame. It is **read-only**: it works
while the store is paused and it is not a steering surface. Humans steer by
talking to the main session, which translates intent into CLI calls; leave
` + "`autoresearch dashboard --refresh 2`" + ` running in a second terminal or tmux
pane while you drive research.

` + "`autoresearch dashboard --json`" + ` emits a structured snapshot for external
tooling (` + "`--refresh`" + ` is refused in JSON mode — use a polling loop
externally).

` + "`autoresearch log --follow --json`" + ` emits JSONL (one event per line) as
new events arrive.

## When you're stuck

- ` + "`autoresearch dashboard`" + ` for a composite snapshot
- ` + "`autoresearch status`" + ` for current counters and pause state
- ` + "`autoresearch log --tail 40`" + ` for what just happened
- ` + "`autoresearch tree`" + ` for the hypothesis graph
- ` + "`autoresearch hypothesis show <id>`" + ` / ` + "`experiment show`" + ` for details
- ` + "`autoresearch artifact list --experiment E-XXXX`" + ` for raw evidence

<!-- autoresearch:managed-end -->
`
