package integration

import (
	"bytes"
	"strings"
)

// EmbeddedCodexAgents returns role briefs derived from the Claude prompts but
// rewritten for Codex's AGENTS.md/.codex convention.
func EmbeddedCodexAgents() ([]AgentFile, error) {
	agents, err := EmbeddedAgents()
	if err != nil {
		return nil, err
	}
	out := make([]AgentFile, 0, len(agents))
	for _, a := range agents {
		out = append(out, AgentFile{
			Name:     a.Name,
			Filename: a.Filename,
			Content:  codexAgentContent(a.Content),
		})
	}
	return out, nil
}

func codexAgentContent(src []byte) []byte {
	text := string(src)
	text = strings.ReplaceAll(text, "autoresearch claude agents install", "autoresearch codex agents install")
	text = strings.ReplaceAll(text, ".claude/autoresearch.md", ".codex/autoresearch.md")
	text = strings.ReplaceAll(text, "@.codex/autoresearch.md", ".codex/autoresearch.md")

	frontmatterEnd := strings.Index(text[4:], "\n---\n")
	if strings.HasPrefix(text, "---\n") && frontmatterEnd >= 0 {
		body := text[4+frontmatterEnd+5:]
		var header bytes.Buffer
		header.WriteString("# ")
		header.WriteString(agentHeadingName(src))
		header.WriteString("\n\n")
		header.WriteString("This brief is generated by `autoresearch codex agents install`.\n")
		header.WriteString("Read `.codex/autoresearch.md` first, then follow the role contract below.\n\n")
		header.WriteString(strings.TrimLeft(body, "\n"))
		text = header.String()
	}
	if !strings.HasSuffix(text, "\n") {
		text += "\n"
	}
	return []byte(text)
}

func agentHeadingName(src []byte) string {
	text := string(src)
	const key = "name: "
	for _, line := range strings.Split(text, "\n") {
		if strings.HasPrefix(line, key) {
			return strings.TrimSpace(strings.TrimPrefix(line, key))
		}
	}
	return "research-role"
}

// InstallCodexAgents writes the derived role briefs into
// <projectDir>/.codex/agents/.
func InstallCodexAgents(projectDir string) (AgentInstallResult, error) {
	agents, err := EmbeddedCodexAgents()
	if err != nil {
		return AgentInstallResult{}, err
	}
	return installAgentFiles(projectDir, ".codex/agents", agents)
}

// PreviewCodexAgents reports what InstallCodexAgents WOULD write.
func PreviewCodexAgents(projectDir string) (AgentInstallResult, error) {
	agents, err := EmbeddedCodexAgents()
	if err != nil {
		return AgentInstallResult{}, err
	}
	return previewAgentFiles(projectDir, ".codex/agents", agents)
}
