package integration

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

type agentFrontmatter struct {
	Name        string `yaml:"name"`
	Description string `yaml:"description"`
	Tools       string `yaml:"tools"`
}

// EmbeddedCodexAgents returns Codex custom-agent configs derived from the
// embedded Claude prompts but rewritten for Codex's AGENTS.md/.codex
// convention.
func EmbeddedCodexAgents() ([]AgentFile, error) {
	agents, err := EmbeddedAgents()
	if err != nil {
		return nil, err
	}
	out := make([]AgentFile, 0, len(agents))
	for _, a := range agents {
		content, err := codexAgentContent(a.Content)
		if err != nil {
			return nil, fmt.Errorf("rewrite codex agent %s: %w", a.Name, err)
		}
		out = append(out, AgentFile{
			Name:     a.Name,
			Filename: strings.TrimSuffix(a.Filename, ".md") + ".toml",
			Content:  content,
		})
	}
	return out, nil
}

func codexAgentContent(src []byte) ([]byte, error) {
	fm, body, err := parseAgentMarkdown(src)
	if err != nil {
		return nil, err
	}
	body = strings.ReplaceAll(body, "autoresearch install claude agents", "autoresearch install codex agents")
	body = strings.ReplaceAll(body, "@.claude/autoresearch.md", ".codex/autoresearch.md")
	body = strings.ReplaceAll(body, ".claude/autoresearch.md", ".codex/autoresearch.md")
	body = strings.TrimLeft(body, "\n")
	body = "Read `.codex/autoresearch.md` first, then follow the role contract below.\n\n" +
		"Codex custom-agent execution model:\n" +
		"- Treat this as a leaf autoresearch role. Do not spawn another `research-orchestrator` or any other autoresearch custom agent from inside it.\n" +
		"- Do not assume nested child sessions expose `spawn_agent`, `send_input`, `wait_agent`, or the same custom `agent_type` names.\n" +
		"- If the workflow needs another autoresearch custom agent, return to the parent/main session with an explicit handoff instead of attempting nested delegation.\n" +
		"- Generic helper delegation explicitly called for below (for example a coder helper in an experiment worktree) is still allowed.\n\n" +
		body
	if strings.Contains(body, "'''") {
		return nil, fmt.Errorf("developer instructions for %s contain TOML literal delimiter", fm.Name)
	}
	sandboxMode := "read-only"
	if agentNeedsWriteSandbox(fm.Tools) {
		sandboxMode = "workspace-write"
	}
	if !strings.HasSuffix(body, "\n") {
		body += "\n"
	}
	var out strings.Builder
	out.WriteString("# This custom agent is generated by `autoresearch install codex agents`.\n")
	out.WriteString("# Edits here will be overwritten on the next init / refresh.\n")
	out.WriteString("# If you want different behavior, create a sibling custom agent with a different name.\n\n")
	fmt.Fprintf(&out, "name = %q\n", fm.Name)
	fmt.Fprintf(&out, "description = %q\n", fm.Description)
	fmt.Fprintf(&out, "sandbox_mode = %q\n", sandboxMode)
	out.WriteString("developer_instructions = '''\n")
	out.WriteString(body)
	out.WriteString("'''\n")
	return []byte(out.String()), nil
}

func parseAgentMarkdown(src []byte) (agentFrontmatter, string, error) {
	text := string(src)
	if !strings.HasPrefix(text, "---\n") {
		return agentFrontmatter{}, "", fmt.Errorf("missing YAML frontmatter")
	}
	frontmatterEnd := strings.Index(text[4:], "\n---\n")
	if frontmatterEnd < 0 {
		return agentFrontmatter{}, "", fmt.Errorf("unterminated YAML frontmatter")
	}
	frontmatter := text[4 : 4+frontmatterEnd]
	body := text[4+frontmatterEnd+5:]
	var fm agentFrontmatter
	if err := yaml.Unmarshal([]byte(frontmatter), &fm); err != nil {
		return agentFrontmatter{}, "", fmt.Errorf("parse YAML frontmatter: %w", err)
	}
	if fm.Name == "" {
		return agentFrontmatter{}, "", fmt.Errorf("missing frontmatter name")
	}
	if fm.Description == "" {
		return agentFrontmatter{}, "", fmt.Errorf("missing frontmatter description")
	}
	return fm, body, nil
}

func agentNeedsWriteSandbox(tools string) bool {
	for _, part := range strings.Split(tools, ",") {
		part = strings.TrimSpace(part)
		if part == "Edit" || part == "Write" {
			return true
		}
	}
	return false
}

// InstallCodexAgents writes the derived custom-agent configs into
// <projectDir>/.codex/agents/.
func InstallCodexAgents(projectDir string) (AgentInstallResult, error) {
	agents, err := EmbeddedCodexAgents()
	if err != nil {
		return AgentInstallResult{}, err
	}
	res, err := installAgentFiles(projectDir, ".codex/agents", agents)
	if err != nil {
		return AgentInstallResult{}, err
	}
	if err := removeLegacyCodexMarkdownAgents(res.Dir, agents); err != nil {
		return AgentInstallResult{}, err
	}
	return res, nil
}

// PreviewCodexAgents reports what InstallCodexAgents WOULD write.
func PreviewCodexAgents(projectDir string) (AgentInstallResult, error) {
	agents, err := EmbeddedCodexAgents()
	if err != nil {
		return AgentInstallResult{}, err
	}
	return previewAgentFiles(projectDir, ".codex/agents", agents)
}

func removeLegacyCodexMarkdownAgents(dir string, agents []AgentFile) error {
	for _, a := range agents {
		legacyName := strings.TrimSuffix(a.Filename, filepath.Ext(a.Filename)) + ".md"
		legacy := filepath.Join(dir, legacyName)
		if err := os.Remove(legacy); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("remove legacy codex agent %s: %w", legacy, err)
		}
	}
	return nil
}
